### ISSUE TITLE
Support tile properties for animated tiles

### ISSUE THREAD

**Issue by noahgibbs** [shawn42/tmx#8]
Tiled supports ManaWorld/Evol-style animated terrain tiles via individual tile properties. It would be good to support loading those properties from the tileset file. Right now tmx seems to just ignore those.

Example TMX file: https://gitlab.com/evol/clientdata/blob/master/maps/000-1.tmx
TSX it is using: https://gitlab.com/evol/clientdata/blob/master/graphics/tilesets/water-calm.tsx

You can clone evol/clientdata, load the TMX file into Tiled and see what it's supposed to look like. But mostly it's just some properties that tmx currently isn't parsing. They don't need complicated processing, just to be included in the output.

**Comment by shawn42** [comment]
:+1: 

This looks like a nice feature to add. I won't have a chance to get to it anytime soon. @burtlo you want to take a stab at this? Otherwise, I'm always accepting pull requests @noahgibbs  ;)

**Comment by noahgibbs** [comment]
I've started working on a pull request, but it may take me some time. I first need to upgrade all the RSpec stuff that has changed in this code :-/

Turns out that "be_true" was deprecated and "have" and "its" moved into separate gems.

**Comment by noahgibbs** [comment]
Pull request submitted.

**Comment by noahgibbs** [comment]
Oh hey, this PR got merged awhile back. Closing.
